#!/usr/bin/env python3
"""
Bundle answer vectors, descriptions, and image paths into a single JS file the
static quiz site can load via a plain <script> tag (works over file://, no
server or fetch/CORS needed).

Output: site/quiz_data.js  ->  window.QUIZ_DATA = { statements, keys, dolls }
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
ANSWERS_DIR = ROOT / "answers"
DESC_DIR = ROOT / "descriptions"
SITE_DIR = ROOT / "site"
MANIFEST = ROOT / "image_manifest.json"

ALL_KEYS = [f"Q{i}" for i in range(1, 21)] + [f"P{i}" for i in range(1, 68)]

# Pulled verbatim from quiz.py so the web quiz asks the exact same statements.
from quiz import STATEMENT_MAP  # noqa: E402

HEADER_RE = re.compile(r"^[A-Z][A-Z'’ ]+$")


def parse_description(text: str) -> dict[str, str]:
    """Split a description .md into its uppercase-headed sections."""
    sections: dict[str, str] = {}
    current = None
    buf: list[str] = []

    def flush():
        if current is not None:
            sections[current] = " ".join(buf).strip()

    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if HEADER_RE.match(stripped) and len(stripped) < 40:
            flush()
            current = stripped
            buf = []
        else:
            buf.append(stripped)
    flush()
    return sections


def main() -> None:
    manifest = json.loads(MANIFEST.read_text())
    dolls = []

    for path in sorted(ANSWERS_DIR.glob("*.json")):
        name = path.stem
        try:
            data = json.loads(path.read_text())
        except Exception:
            continue
        if not all(
            k in data and isinstance(data[k], int) and data[k] in (1, 2, 3, 4)
            for k in ALL_KEYS
        ):
            continue

        desc_path = DESC_DIR / f"{name}.md"
        sections = parse_description(desc_path.read_text()) if desc_path.exists() else {}

        img = manifest.get(name, {}).get("local")
        if not img or not (ROOT / img).exists():
            continue

        dolls.append({
            "name": name,
            "image": img,
            "vector": {k: data[k] for k in ALL_KEYS},
            "whatShesLike": sections.get("WHAT SHE'S LIKE", ""),
            "iSeeYou": sections.get("I SEE YOU", ""),
        })

    payload = {
        "statements": STATEMENT_MAP,
        "keys": ALL_KEYS,
        "dolls": dolls,
    }

    SITE_DIR.mkdir(exist_ok=True)
    out = SITE_DIR / "quiz_data.js"
    out.write_text(
        "// Auto-generated by build_site_data.py. Do not edit by hand.\n"
        "window.QUIZ_DATA = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    print(f"Wrote {out} with {len(dolls)} dolls.")


if __name__ == "__main__":
    main()
